application: nail-chiodo
version: 1
runtime: go
api_version: go1

handlers:
- url: /media
  static_dir: static/media
- url: /.*
  script: _go_app

error_handlers:
- file: static/error.html

skip_files:
- ^Makefile$
- ^(.*/)?\..*$
- ^(.*)\.sublime-project$
- ^(.*)\.sublime-workspace$
